version: '3'
services:
  vprodb:
    image: 750232146652.dkr.ecr.us-east-1.amazonaws.com/vprofiledb:latest
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      
  vproapp:
    image: 750232146652.dkr.ecr.us-east-1.amazonaws.com/vprofileappimg:latest
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: 750232146652.dkr.ecr.us-east-1.amazonaws.com/vprofileweb:latest
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
